version: "0.2"
language:
  - en
  - ru
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - cfeee1e5e4e00a
  - clsx
  - daisyui
  - fastify
  - heroicons
  - leadpogrommer
  - netops
  - preact
  - preshared
  - tailwindcss
  - парсингом
ignoreWords: []
import: []
